# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'glovo-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'HAActionSheet'

  # Pods for glovo-app

  target 'glovo-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
